### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Alex-Akastolov/grid-template#1]
1)
Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам CSS, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/173215317-f4e06cae-a507-4eb6-9735-92bd093a56b4.png)

**Comment by Alex-Akastolov** [comment]
Исправил.
